### ISSUE TITLE
Qt 6.6 compatibility?

### ISSUE THREAD

**Issue by Selur** [captainayy/BDSup2SubPlusPlus#3]
Seeing that even Ubuntu 22.04 supports Qt6.6 nowadays, I was wondering if you plan to adjust the project to compile with Qt.6.6?
In case you plan to port this to Qt 6.6 I attached a modified version I build on the release of https://github.com/amichaeltm/BDSup2SubPlusPlus
[BDSup2SubPlusPlus_mine.zip](https://github.com/captainayy/BDSup2SubPlusPlus/files/13749242/BDSup2SubPlusPlus_mine.zip)
maybe that helps.

**Comment by Selur** [comment]
there is something wrong with my version

**Comment by TheGreatMcPain** [comment]
Hi, I'm attempting to get this working with Qt6 as well, but I've noticed I can't open BDXML files.

I was wondering if that was the issue you're running into.

**Comment by TheGreatMcPain** [comment]
Okay, I've started to notice that the way XML files are handled in QT6 is very different, but the old APIs are still available via the `qt5compat` module.

There's still things that need to be changed to build with `qt5compat`, but at least the XML stuff won't need redone.

**Comment by Selur** [comment]
I have never tried XML files (only use it for vob -> sup conversion), but my fork https://github.com/Selur/BDSup2SubPlusPlus does work with current Qt

**Comment by TheGreatMcPain** [comment]
Yeah, I tried your fork for a bit.  It does work for most things, but it can't read BDXML files.

Using `qt5compat` and letting it use the old XML classes should fix that for now.

**Comment by TheGreatMcPain** [comment]
Yeah, I tried your fork for a bit.  It does work for most things, but it can't read BDXML files.

Using `qt5compat` and letting it use the old XML classes should fix that for now.
